export type DisplaySettings={words:number;characters:number;lines:number;width:number;horizontal:string;vertical:string};
export const defaultDisplay:DisplaySettings={words:6,characters:38,lines:6,width:576,horizontal:'center',vertical:'center'};
export function normalizeDisplay(value:Partial<DisplaySettings>):DisplaySettings{
 const integer=(n:unknown,lo:number,hi:number,fallback:number)=>typeof n==='number'&&Number.isFinite(n)?Math.max(lo,Math.min(hi,Math.round(n))):fallback;
 return {words:integer(value.words,1,8,6),characters:integer(value.characters,12,38,38),lines:integer(value.lines,2,6,6),width:integer(value.width,360,576,576),horizontal:['left','center','right'].includes(value.horizontal??'')?value.horizontal!:'center',vertical:['top','center','bottom'].includes(value.vertical??'')?value.vertical!:'center'};
}
export function geometry(s:DisplaySettings){const height=Math.min(288,72+s.lines*32);return {width:s.width,height,x:s.horizontal==='left'?0:s.horizontal==='right'?576-s.width:Math.floor((576-s.width)/2),y:s.vertical==='top'?0:s.vertical==='bottom'?288-height:Math.floor((288-height)/2)};}
export function mountDisplay(onChange:(s:DisplaySettings)=>void){
 let settings={...defaultDisplay};try{settings=normalizeDisplay(JSON.parse(localStorage.getItem('coach-display-v1')??'{}'));}catch{}
 const root=document.querySelector<HTMLElement>('#display-settings')!;
 root.innerHTML=`<summary>Customize glasses window</summary><label>Maximum words per line <input id="words" type="range" min="1" max="8"><output id="words-value"></output></label><label>Maximum characters per line <input id="characters" type="range" min="12" max="38"><output id="characters-value"></output></label><label>Lines per page <input id="lines" type="range" min="2" max="6"><output id="lines-value"></output></label><label>Window width <select id="width"><option value="360">Narrow</option><option value="456">Medium</option><option value="576">Full width</option></select></label><label>Horizontal position<select id="horizontal"><option>left</option><option>center</option><option>right</option></select></label><label>Vertical position<select id="vertical"><option>top</option><option>center</option><option>bottom</option></select></label><button id="reset-display">Reset display</button><p>Long words may wrap earlier to fit. The glasses use a fixed font. Position changes are most visible with a narrow window and fewer lines.</p><div id="display-canvas"><pre id="display-sample"></pre></div>`;
 function draw(){for(const key of ['words','characters','lines','width','horizontal','vertical'] as const){(root.querySelector('#'+key) as HTMLInputElement).value=String(settings[key]);}root.querySelector('#words-value')!.textContent=String(settings.words);root.querySelector('#lines-value')!.textContent=String(settings.lines);root.querySelector('#characters-value')!.textContent=String(settings.characters);const g=geometry(settings);const sample=root.querySelector<HTMLElement>('#display-sample')!;Object.assign(sample.style,{left:`${g.x/576*100}%`,top:`${g.y/288*100}%`,width:`${g.width/576*100}%`,height:`${g.height/288*100}%`});sample.textContent='ANSWER\n\n'+Array.from({length:settings.lines},()=>Array.from({length:Math.min(settings.words,4)},()=> 'word').join(' ')).join('\n');onChange(settings);}
 root.querySelectorAll('input,select').forEach(el=>el.addEventListener('change',()=>{const key=el.id as keyof DisplaySettings;const value=(el as HTMLInputElement).value;settings=normalizeDisplay({...settings,[key]:['words','characters','lines','width'].includes(key)?Number(value):value});try{localStorage.setItem('coach-display-v1',JSON.stringify(settings));}catch{}draw();}));
 root.querySelector<HTMLButtonElement>('#reset-display')!.onclick=()=>{settings={...defaultDisplay};try{localStorage.removeItem('coach-display-v1');}catch{}draw();};draw();
 return {read:()=>settings,restore:(value:Partial<DisplaySettings>)=>{settings=normalizeDisplay(value);draw();}};
}
