import {it,expect} from 'vitest';
import {LiveState} from './live-state';
import {lineForSpeech} from './speaker';
import {ProfileMemory,type SavedProfile} from './saved-settings';
it('completed mode holds the old answer until the full new answer is done',()=>{const s=new LiveState();s.answer='Old answer';s.presentation='complete';s.apply({type:'answer.start',answer_id:'a',question:'Story'});s.apply({type:'answer.delta',answer_id:'a',text:'New '});expect(s.answer).toBe('Old answer');s.apply({type:'answer.delta',answer_id:'a',text:'complete answer'});expect(s.answer).toBe('Old answer');s.apply({type:'answer.done',answer_id:'a',text:'New complete answer'});expect(s.answer).toBe('New complete answer');expect(s.pending).toBe(false);});
it('streams teleprompter text and rejects stale generation events',()=>{const s=new LiveState();s.apply({type:'answer.start',answer_id:'new'});s.apply({type:'answer.delta',answer_id:'old',text:'Wrong'});expect(s.answer).toBe('');s.apply({type:'answer.delta',answer_id:'new',text:'First words'});expect(s.answer).toBe('First words');});
it('moves through lines without losing the final lines and never runs backward in voice follow',()=>{const s=new LiveState();s.wordsPerLine=2;s.linesPerPage=2;s.answer='one two three four five six seven eight nine ten';s.scrollLines(1);expect(s.frame()).toContain('three four');s.followLine(4);expect(s.lineOffset).toBe(3);s.followLine(1);expect(s.lineOffset).toBe(3);s.scrollLines(99);expect(s.frame()).toContain('nine ten');});
it('matches spoken phrases across line boundaries and punctuation, but holds ambiguous speech',()=>{const lines=['I preserve the DELETE','tombstone. Then replay safely.'];expect(lineForSpeech(lines,'preserve the delete tombstone')).toBe(1);expect(lineForSpeech(lines,'What about costs?')).toBeNull();expect(lineForSpeech(['same exact words','same exact words'],'same exact words')).toBeNull();});
it('restores settings per profile and can save settings without retaining a token',()=>{const data=new Map<string,string>();const storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);},removeItem:(k:string)=>{data.delete(k);}};const store=new ProfileMemory(storage,'test');const a:SavedProfile={values:{presentation:'complete'},model:{model:'gpt-4.1',reasoning_effort:'default'},instructions:'Use an example',display:{words:5}};store.save('a',a,'app-token',true);store.save('b',{...a,instructions:'Be concise'},'app-token',true);expect(new ProfileMemory(storage,'test').load('a')?.instructions).toBe('Use an example');expect(store.last()).toBe('b');store.save('a',a,'app-token',false);expect(store.token()).toBe('');store.forget();expect(store.load('a')).toBeUndefined();expect(store.token()).toBe('');});
